-- ============================================================
-- HOSPITAL DATABASE - INDEXES & VIEWS
-- ============================================================

-- ИНДЕКСЫ

CREATE INDEX IDX_PATIENTS_LASTNAME    ON PATIENTS(LAST_NAME);
CREATE INDEX IDX_PATIENTS_BIRTHDATE   ON PATIENTS(BIRTH_DATE);
CREATE INDEX IDX_PATIENTS_CITY        ON PATIENTS(CITY);
CREATE INDEX IDX_PATIENTS_DOCTOR      ON PATIENTS(PRIMARY_DOCTOR_ID);

CREATE INDEX IDX_DOCTORS_SPEC         ON DOCTORS(SPECIALIZATION);
CREATE INDEX IDX_DOCTORS_DEPT         ON DOCTORS(DEPARTMENT);

CREATE INDEX IDX_APPT_PATIENT         ON APPOINTMENTS(PATIENT_ID);
CREATE INDEX IDX_APPT_DOCTOR          ON APPOINTMENTS(DOCTOR_ID);
CREATE INDEX IDX_APPT_DATE            ON APPOINTMENTS(APPOINTMENT_DATE);
CREATE INDEX IDX_APPT_STATUS          ON APPOINTMENTS(STATUS);

CREATE INDEX IDX_PRESC_PATIENT        ON PRESCRIPTIONS(PATIENT_ID);
CREATE INDEX IDX_PRESC_DOCTOR         ON PRESCRIPTIONS(DOCTOR_ID);
CREATE INDEX IDX_PRESC_APPT           ON PRESCRIPTIONS(APPOINTMENT_ID);
CREATE INDEX IDX_PRESC_MEDICINE       ON PRESCRIPTIONS(MEDICINE_NAME);

-- ============================================================
-- ПРЕДСТАВЛЕНИЯ (VIEWS)
-- ============================================================

-- Полная информация о пациенте с лечащим врачом
CREATE OR REPLACE VIEW V_PATIENTS_WITH_DOCTOR AS
SELECT
    p.PATIENT_ID,
    TRIM(p.LAST_NAME || ' ' || p.FIRST_NAME || ' ' || NVL(p.MIDDLE_NAME, '')) AS PATIENT_FIO,
    p.BIRTH_DATE,
    TRUNC(MONTHS_BETWEEN(SYSDATE, p.BIRTH_DATE) / 12) AS AGE,
    p.GENDER,
    p.BLOOD_TYPE,
    p.POLICY_NUMBER,
    p.PHONE,
    p.CITY,
    p.DIAGNOSIS,
    p.ALLERGIES,
    TRIM(d.LAST_NAME || ' ' || d.FIRST_NAME || ' ' || NVL(d.MIDDLE_NAME, '')) AS DOCTOR_FIO,
    d.SPECIALIZATION,
    d.DEPARTMENT
FROM PATIENTS p
LEFT JOIN DOCTORS d ON p.PRIMARY_DOCTOR_ID = d.DOCTOR_ID;

-- Расписание приёмов с ФИО
CREATE OR REPLACE VIEW V_APPOINTMENTS_FULL AS
SELECT
    a.APPOINTMENT_ID,
    a.APPOINTMENT_DATE,
    a.APPOINTMENT_TIME,
    a.DURATION_MIN,
    a.STATUS,
    a.VISIT_TYPE,
    p.LAST_NAME || ' ' || p.FIRST_NAME AS PATIENT_NAME,
    p.PHONE AS PATIENT_PHONE,
    TRUNC(MONTHS_BETWEEN(SYSDATE, p.BIRTH_DATE) / 12) AS PATIENT_AGE,
    d.LAST_NAME || ' ' || d.FIRST_NAME AS DOCTOR_NAME,
    d.SPECIALIZATION,
    d.DEPARTMENT,
    a.COMPLAINTS,
    a.DIAGNOSIS,
    a.RECOMMENDATIONS
FROM APPOINTMENTS a
JOIN PATIENTS p ON a.PATIENT_ID = p.PATIENT_ID
JOIN DOCTORS  d ON a.DOCTOR_ID  = d.DOCTOR_ID;

-- Статистика по врачам
CREATE OR REPLACE VIEW V_DOCTOR_STATS AS
SELECT
    d.DOCTOR_ID,
    d.LAST_NAME || ' ' || d.FIRST_NAME AS DOCTOR_FIO,
    d.SPECIALIZATION,
    d.DEPARTMENT,
    d.EXPERIENCE_YEARS,
    d.CATEGORY,
    COUNT(DISTINCT a.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
    COUNT(DISTINCT CASE WHEN a.STATUS = 'Завершён' THEN a.APPOINTMENT_ID END) AS COMPLETED,
    COUNT(DISTINCT CASE WHEN a.STATUS = 'Отменён'  THEN a.APPOINTMENT_ID END) AS CANCELLED,
    COUNT(DISTINCT p2.PRESCRIPTION_ID) AS TOTAL_PRESCRIPTIONS,
    COUNT(DISTINCT a.PATIENT_ID) AS UNIQUE_PATIENTS
FROM DOCTORS d
LEFT JOIN APPOINTMENTS   a  ON d.DOCTOR_ID = a.DOCTOR_ID
LEFT JOIN PRESCRIPTIONS  p2 ON d.DOCTOR_ID = p2.DOCTOR_ID
GROUP BY d.DOCTOR_ID, d.LAST_NAME, d.FIRST_NAME,
         d.SPECIALIZATION, d.DEPARTMENT, d.EXPERIENCE_YEARS, d.CATEGORY;

-- Активные рецепты
CREATE OR REPLACE VIEW V_ACTIVE_PRESCRIPTIONS AS
SELECT
    pr.PRESCRIPTION_ID,
    p.LAST_NAME || ' ' || p.FIRST_NAME AS PATIENT_NAME,
    d.LAST_NAME || ' ' || d.FIRST_NAME AS DOCTOR_NAME,
    pr.MEDICINE_NAME,
    pr.DOSAGE,
    pr.FREQUENCY,
    pr.DURATION_DAYS,
    pr.ISSUE_DATE,
    pr.EXPIRY_DATE,
    pr.MEDICINE_TYPE,
    pr.IS_DISPENSED,
    pr.NOTES
FROM PRESCRIPTIONS pr
JOIN PATIENTS p ON pr.PATIENT_ID = p.PATIENT_ID
JOIN DOCTORS  d ON pr.DOCTOR_ID  = d.DOCTOR_ID
WHERE pr.EXPIRY_DATE >= SYSDATE;

COMMIT;

PROMPT Индексы и представления созданы!
